//! The tool in hand: each tool's hex model (`pbd_core::hexel`) and the right
//! hand gripping it, held in first person, swaying a little and swinging
//! while a block is being broken.
//!
//! The shapes, the held poses and the hand are data, generated by
//! `tools/gen_held_tools.py` from the approved Hex Tool Bench mockup into
//! `assets/models/held_tools.ron`, which is compiled in. The same generator
//! draws the slot icons from the same hexes, so the icon and the model cannot
//! differ. The sway and the chop are tunables in `assets/config/held.ron`.
//! The fishing line leaves from the rod model's own tip
//! (`openspec/changes/hex-held-tools`).

use crate::config::HeldConfig;
use crate::fish::ToolSlot;
use crate::walking::{WalkingCamera, WalkingReadout};
use bevy::asset::RenderAssetUsages;
use bevy::light::NotShadowCaster;
use bevy::mesh::PrimitiveTopology;
use bevy::prelude::*;
use pbd_core::hexel::{self, Hex, HexelMesh, Prism};
use pbd_core::inventory::Tool;
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;

/// How the tool in hand moves, in `held.ron`.
#[derive(Clone, Copy, Debug, PartialEq, Deserialize, Serialize)]
#[serde(default, deny_unknown_fields)]
pub struct HeldSettings {
    /// The idle sway: amplitude right and up, m, and rate, rad/s (Tenebris).
    pub sway_m: [f32; 2],
    pub sway_rate: [f32; 2],
    /// The chop while a block is being broken (Tenebris): the swing's rate,
    /// rad/s, how far the tool drops, m, and how far it pitches about the
    /// fist, rad.
    pub swing_rate: f32,
    pub swing_drop_m: f32,
    pub swing_pitch_rad: f32,
}

impl Default for HeldSettings {
    fn default() -> Self {
        Self {
            sway_m: [0.006, 0.005],
            sway_rate: [1.3, 1.7],
            swing_rate: 9.0,
            swing_drop_m: 0.06,
            swing_pitch_rad: 0.85,
        }
    }
}

impl HeldSettings {
    pub fn validate(&self) -> Result<(), String> {
        let all = [
            self.sway_m[0],
            self.sway_m[1],
            self.sway_rate[0],
            self.sway_rate[1],
            self.swing_rate,
            self.swing_drop_m,
            self.swing_pitch_rad,
        ];
        if all.iter().any(|v| !v.is_finite() || *v < 0.0) {
            return Err("held: sway and swing are finite and non-negative".into());
        }
        Ok(())
    }
}

/// One tool as `held_tools.ron` holds it. Tool units: x along the handle from
/// the butt, y up the drawing, z out of it. Eye space: metres, x right, y up,
/// -z ahead.
#[derive(Clone, Debug, PartialEq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HeldModel {
    pub tool: String,
    /// The rest pose: where the butt (tool origin) sits, the tool-to-eye
    /// rotation (x, y, z, w) and metres per tool unit.
    pub butt: [f32; 3],
    pub rotation: [f32; 4],
    pub scale: f32,
    /// Where the fist sits in eye space: the chop pivots here.
    pub fist: [f32; 3],
    /// The far end of the tool in eye space: where the fishing line leaves
    /// the rod.
    pub tip: [f32; 3],
    pub hexes: Vec<Hex>,
    /// The hand's prisms, in tool units.
    pub hand: Vec<Prism>,
}

impl HeldModel {
    /// The rest pose as a transform from tool units to eye space.
    pub fn rest(&self) -> Transform {
        Transform {
            translation: self.butt.into(),
            rotation: Quat::from_array(self.rotation).normalize(),
            scale: Vec3::splat(self.scale),
        }
    }
}

/// Every tool's model, and the grid they are drawn on.
#[derive(Clone, Debug, PartialEq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HeldModels {
    /// Hex centre spacing, tool units.
    pub spacing: f32,
    pub tools: Vec<HeldModel>,
}

impl HeldModels {
    /// Every tool present once and every number sound.
    pub fn validate(&self) -> Result<(), String> {
        if !(self.spacing.is_finite() && self.spacing > 0.0) {
            return Err("held_tools: spacing is positive".into());
        }
        for tool in Tool::ALL {
            let n = self.tools.iter().filter(|m| m.tool == key(tool)).count();
            if n != 1 {
                return Err(format!("held_tools: {} appears {n} times", key(tool)));
            }
        }
        for m in &self.tools {
            let numbers = m
                .butt
                .iter()
                .chain(&m.rotation)
                .chain(&m.fist)
                .chain(&m.tip)
                .chain(std::iter::once(&m.scale));
            if numbers.into_iter().any(|v| !v.is_finite()) || m.scale <= 0.0 {
                return Err(format!("held_tools.{}: a pose number is not sound", m.tool));
            }
            if m.hexes.is_empty() || m.hexes.iter().any(|h| h.depth.is_nan() || h.depth <= 0.0) {
                return Err(format!(
                    "held_tools.{}: hexes need a positive depth",
                    m.tool
                ));
            }
            if m.hand.is_empty() || !m.hand.iter().all(Prism::is_sound) {
                return Err(format!("held_tools.{}: a hand prism is not sound", m.tool));
            }
        }
        Ok(())
    }

    pub fn get(&self, tool: Tool) -> &HeldModel {
        self.tools
            .iter()
            .find(|m| m.tool == key(tool))
            .expect("held_tools.ron has every tool: validated on load")
    }
}

/// A tool's name in `held_tools.ron`.
fn key(tool: Tool) -> &'static str {
    match tool {
        Tool::Rod => "rod",
        Tool::Shovel => "shovel",
        Tool::Pickaxe => "pickaxe",
        Tool::Axe => "axe",
    }
}

/// The generated models, parsed and checked once.
pub fn models() -> &'static HeldModels {
    static MODELS: OnceLock<HeldModels> = OnceLock::new();
    MODELS.get_or_init(|| {
        let models: HeldModels =
            ron::from_str(include_str!("../../../assets/models/held_tools.ron"))
                .expect("assets/models/held_tools.ron parses: tools/gen_held_tools.py writes it");
        models
            .validate()
            .expect("assets/models/held_tools.ron is sound");
        models
    })
}

/// Where the fishing line leaves the rod, in eye space: the rod model's own
/// tip.
pub fn rod_tip() -> Vec3 {
    models().get(Tool::Rod).tip.into()
}

/// The light the hand is shaded against, in eye space: from above, a little
/// right and toward the eye.
const HAND_LIGHT: Vec3 = Vec3::new(0.3, 0.8, 0.55);

/// A tool's hex mesh and its hand's mesh, in tool units.
pub fn meshes(model: &HeldModel, spacing: f32) -> (HexelMesh, HexelMesh) {
    let tool = hexel::mesh(&model.hexes, spacing);
    let light = model.rest().rotation.inverse() * HAND_LIGHT.normalize();
    let mut hand = HexelMesh::default();
    for part in &model.hand {
        hexel::prism(part, light, &mut hand);
    }
    (tool, hand)
}

/// Whether a block is being broken, so the tool in hand chops. Written by
/// whoever runs the digging.
#[derive(Resource, Default, Clone, Copy, Debug)]
pub struct Swinging(pub bool);

/// A held tool, one per tool, a child of the walking camera: it carries the
/// pose, and its two children are the tool's mesh and the hand's.
#[derive(Component)]
pub struct Held {
    tool: Tool,
    rest: Transform,
    fist: Vec3,
}

pub struct HeldPlugin;

impl Plugin for HeldPlugin {
    fn build(&self, app: &mut App) {
        app.init_resource::<Swinging>()
            .add_systems(Update, (spawn, hold).chain());
    }
}

fn bevy_mesh(built: HexelMesh) -> Mesh {
    let mut mesh = Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
    );
    mesh.insert_attribute(Mesh::ATTRIBUTE_POSITION, built.positions);
    mesh.insert_attribute(Mesh::ATTRIBUTE_NORMAL, built.normals);
    mesh.insert_attribute(Mesh::ATTRIBUTE_COLOR, built.colours);
    mesh
}

/// Build the four tools and their hands once the walking camera exists,
/// hidden.
fn spawn(
    mut commands: Commands,
    cameras: Query<Entity, With<WalkingCamera>>,
    existing: Query<(), With<Held>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    if !existing.is_empty() {
        return;
    }
    let Some(camera) = cameras.iter().next() else {
        return;
    };
    // Unlit, with the shade baked per face: Tenebris draws its tool unlit so
    // it reads at night and in a cave, and so does this.
    let material = materials.add(StandardMaterial {
        base_color: Color::WHITE,
        unlit: true,
        fog_enabled: false,
        ..default()
    });
    let all = models();
    for tool in Tool::ALL {
        let model = all.get(tool);
        let rest = model.rest();
        let (tool_mesh, hand_mesh) = self::meshes(model, all.spacing);
        let holder = commands
            .spawn((
                Name::new(format!("{} in hand", tool.name())),
                Held {
                    tool,
                    rest,
                    fist: model.fist.into(),
                },
                rest,
                Visibility::Hidden,
            ))
            .with_children(|parent| {
                for (part, built) in [("tool", tool_mesh), ("hand", hand_mesh)] {
                    parent.spawn((
                        Name::new(part),
                        Mesh3d(meshes.add(bevy_mesh(built))),
                        MeshMaterial3d(material.clone()),
                        Transform::IDENTITY,
                        Visibility::Inherited,
                        NotShadowCaster,
                    ));
                }
            })
            .id();
        commands.entity(camera).add_child(holder);
    }
}

/// Show the tool in hand, sway it, and chop while a block is being broken.
fn hold(
    settings: Res<HeldConfig>,
    tools: Res<ToolSlot>,
    walking: Option<Res<WalkingReadout>>,
    swinging: Res<Swinging>,
    time: Res<Time>,
    mut phase: Local<f32>,
    mut models: Query<(&Held, &mut Transform, &mut Visibility)>,
) {
    let s = &settings.0;
    let on_foot = walking.is_some_and(|w| w.active);
    // The chop advances while breaking and snaps back when it stops, as
    // Tenebris's does; a tool changed mid-swing does not pop.
    *phase = if swinging.0 {
        *phase + time.delta_secs() * s.swing_rate
    } else {
        0.0
    };
    let chop = if *phase > 0.0 {
        phase.sin().max(-0.2)
    } else {
        0.0
    };
    let t = time.elapsed_secs();
    let sway = Vec3::new(
        (t * s.sway_rate[0]).sin() * s.sway_m[0],
        (t * s.sway_rate[1]).cos() * s.sway_m[1],
        0.0,
    );
    for (held, mut transform, mut visibility) in &mut models {
        let shown = on_foot && tools.held() == held.tool;
        let want = if shown {
            Visibility::Inherited
        } else {
            Visibility::Hidden
        };
        if *visibility != want {
            *visibility = want;
        }
        if !shown {
            continue;
        }
        // The chop pitches the tool and the hand about the fist and drops
        // them: the rod does not chop, it casts.
        let chop = if held.tool == Tool::Rod { 0.0 } else { chop };
        let pitch = Quat::from_rotation_x(-chop * s.swing_pitch_rad);
        let mut pose = held.rest;
        pose.translation = held.fist + pitch * (pose.translation - held.fist) + sway
            - Vec3::Y * chop * s.swing_drop_m;
        pose.rotation = pitch * pose.rotation;
        *transform = pose;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated file parses and is sound, every tool is one connected
    /// piece (a part that fell off would float in the hand), and its meshes
    /// are built.
    #[test]
    fn every_tool_is_one_piece_with_a_hand() {
        let all = models();
        for tool in Tool::ALL {
            let model = all.get(tool);
            assert!(model.hexes.len() > 100, "{tool:?}: {}", model.hexes.len());
            let pieces = hexel::pieces(&model.hexes);
            assert_eq!(pieces.len(), 1, "{tool:?} is in pieces: {pieces:?}");
            let (tool_mesh, hand_mesh) = meshes(model, all.spacing);
            assert!(tool_mesh.triangles() > model.hexes.len() * 12);
            assert_eq!(hand_mesh.triangles(), model.hand.len() * 24);
            assert!(
                tool_mesh
                    .positions
                    .iter()
                    .chain(&hand_mesh.positions)
                    .flatten()
                    .all(|v| v.is_finite())
            );
        }
    }

    /// A handle is whole rows: row 0 runs unbroken from the butt, so the
    /// handle is a straight line of hexes and not a zigzag.
    #[test]
    fn a_handle_is_whole_rows() {
        for tool in Tool::ALL {
            let model = models().get(tool);
            let row: std::collections::BTreeSet<i32> = model
                .hexes
                .iter()
                .filter(|h| h.r == 0)
                .map(|h| h.q)
                .collect();
            let (first, last) = (*row.first().unwrap(), *row.last().unwrap());
            assert!(first <= 0, "{tool:?}: the butt is on row 0");
            assert_eq!(
                row.len() as i32,
                last - first + 1,
                "{tool:?}: row 0 has a gap"
            );
            assert!(
                last as f32 * models().spacing > 10.0,
                "{tool:?}: a long handle"
            );
        }
    }

    /// The fishing line leaves from the tip of the rod that is drawn: the
    /// rod's farthest hex, placed by its rest pose, is at the tip.
    #[test]
    fn the_line_leaves_the_rod_model_tip() {
        let rod = models().get(Tool::Rod);
        let far = rod
            .hexes
            .iter()
            .map(|h| hexel::centre(h.q, h.r, models().spacing))
            .max_by(|a, b| a.x.total_cmp(&b.x))
            .unwrap();
        let tip = rod.rest().transform_point(far.extend(0.0));
        let near = models().spacing * rod.scale;
        assert!(tip.distance(rod_tip()) < near, "{tip} vs {}", rod_tip());
    }

    /// The fist, where the chop pivots, is on the handle: the hand holds the
    /// tool it is drawn with.
    #[test]
    fn the_fist_is_on_the_handle() {
        for tool in Tool::ALL {
            let model = models().get(tool);
            let rest = model.rest();
            let fist = rest
                .compute_affine()
                .inverse()
                .transform_point3(model.fist.into());
            assert!(
                fist.x > 0.0 && fist.y.abs() < 0.1 && fist.z.abs() < 0.1,
                "{tool:?}: {fist}"
            );
        }
    }

    /// With the pickaxe in hand on foot, the pickaxe's holder is shown and no
    /// other; flying, none is. Each holder carries the tool and the hand.
    #[test]
    fn only_the_tool_in_hand_is_shown_with_its_hand() {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins)
            .init_resource::<Assets<Mesh>>()
            .init_resource::<Assets<StandardMaterial>>()
            .insert_resource(HeldConfig::default())
            .insert_resource(WalkingReadout {
                active: true,
                ..default()
            })
            .init_resource::<Swinging>()
            .insert_resource({
                let mut slot = ToolSlot::default();
                slot.hold(Tool::Pickaxe);
                slot
            })
            .add_systems(Update, (spawn, hold).chain());
        app.world_mut().spawn((WalkingCamera, Transform::default()));
        app.update();
        app.update();
        let mut holders = app.world_mut().query::<(&Held, &Visibility, &Children)>();
        let rows: Vec<(Tool, bool, usize)> = holders
            .iter(app.world())
            .map(|(h, v, c)| (h.tool, *v != Visibility::Hidden, c.len()))
            .collect();
        assert_eq!(rows.len(), 4);
        for (tool, shown, children) in &rows {
            assert_eq!(*shown, *tool == Tool::Pickaxe, "{tool:?}");
            assert_eq!(*children, 2, "{tool:?}: the tool and the hand");
        }
        app.world_mut().resource_mut::<WalkingReadout>().active = false;
        app.update();
        let shown = holders
            .iter(app.world())
            .filter(|(_, v, _)| **v != Visibility::Hidden)
            .count();
        assert_eq!(shown, 0, "nothing in hand while flying");
    }

    #[test]
    fn the_defaults_validate() {
        HeldSettings::default().validate().unwrap();
        let bad = HeldSettings {
            swing_rate: -1.0,
            ..Default::default()
        };
        assert!(bad.validate().is_err());
    }
}
